### PR TITLE
Fixed undefined is not a function error when using breeze-kendo - angular

### PR DESCRIPTION
**Pull request by robi26**
When using breeze-kendo with angular.js the executeQuery (line 65) throws an error: undefined is not a function.
Using breeze call without promises fixes the error.

### CODE REVIEW

**Comment by rondefreitas** [comment]
Can you resubmit  a pull request without changing tabs/spacing?  The diff is showing nearly every line changed

**Comment by robi26** [comment]
Hi
No problem, I'll do it on Momday. 

Stephan

**Comment by robi26** [comment]
Please see updated version.
Sorry for having wrong line breaks / formatting. The editor was reformatting the document on saving.

**Comment by datanotion** [comment]
@robi26 - This fails for me.  Shouldn't lines 73, 74, and 75 also be removed?

**Comment by pascalberger** [comment]
Since Telerik don't seem to be willing to consider PRs for this project I've created a forked version of this project containing this PR at https://github.com/iozag/breeze-kendo

**Pull request closed without merging**
